version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/payara-micro-maven-archetype"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    
  - package_manager: "java:maven"
    directory: "/payara-micro-maven-plugin"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"